pipeline{

	agent{
		node { label 'DEVLINSLAVES' }
	}
    parameters {
          gitParameter(branch: '',
                     branchFilter: '',
                     defaultValue: 'origin/main',
                     description: 'Branch Name',
                     name: 'BRANCH',
                     selectedValue: 'NONE',
                     sortMode: 'NONE',
                     tagFilter: '',
                     type: 'PT_BRANCH')
    }
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '4'))
        timestamps()
    }
	environment {
        HOME = '.'
        TIMESTAMP = new java.text.SimpleDateFormat('yyyyMMddHHmmss').format(new Date())
    }
    stages {
        stage('Init') {
            steps{
                script {
						echo "Cleaning work space"
				        cleanWs()
				        MAVEN_PROFILE = '-Pdocker'
						SERVICES_TO_DEPLOY= 'weather-app'
                    }
                }
        }
		stage('Fetch sources'){
		  steps{
			    dir('sources'){
                    deleteDir()
       				checkout([
                				$class                           : 'GitSCM',
                				branches                         : [[name: "${BRANCH}"]],
                				doGenerateSubmoduleConfigurations: false,
                				extensions                       : [],
                				submoduleCfg                     : [],
                				userRemoteConfigs                : [[credentialsId: 'git-user', url: "https://github.com/aakash-deep-sharma/weather-app"]],
                				extensions                       : [[$class: 'LocalBranch', localBranch: 'main']]
        			])
				}
			}
		}
		stage('brick frontend build'){
			steps {
                script {
    			    dir("sources/com.pub.sapient.fe/src/main/www"){
		        	    nodejs(configId: 'NPMRC-GLOBAL', nodeJSInstallationName: 'NODE_22.21.1') {
			                sh """
								npm cache clean -f
								npm config fix
								npm config ls -l
								node -v
								npm -v
                                npm i --loglevel=error --unsafe-perm --force
    			                npm run-script build -c=production
				            """
		            	}
		            }
                }
			}
		}
		stage('brick backend build'){
			steps{
                script {
					    withMaven(
						    jdk: 'openjdk_17-hotspot',
							maven: 'Maven 3.9.1',
						    mavenSettingsConfig: 'mvn-settings', 
						    mavenLocalRepo: '/opt/maven/weather/.repository', 
						    tempBinDir: ''
					    ){
						    sh """
						        java -version
							    javac -version
	        					export PATH=$MVN_CMD_DIR:$PATH
	        					mvn clean install -f sources/com.pub.sapient/pom.xml
	        					mvn clean install -f sources/com.pub.sapient.fe/pom.xml
	        					mvn clean deploy ${MAVEN_PROFILE} -f sources/com.pub.sapient.be/pom.xml
						    """
					    }
                }
			}
		}
	}
    post {																											 
        aborted{
            sleep(1)
            script{currentBuild.result='ABORTED'}
            logstashSend failBuild: false, maxLines: 1000
        }
        failure{
            sleep(1)
            script{currentBuild.result='FAILURE'}
            logstashSend failBuild: false, maxLines: 1000
        }
        success{
            sleep(1)
            script{currentBuild.result='SUCCESS'}
            logstashSend failBuild: false, maxLines: 1000
        }
    }
}