spring:
  application:
    name: publicissapient

logging:
  level:
    io.github.resilience4j.retry: TRACE
    io.github.resilience4j.circuitbreaker: TRACE


management:
  endpoints:
    web:
      exposure:
        include: health,env,configprops

weather:
  api:
    key: ${OPENWEATHER_API_KEY:e4b35f5360ad47afee8acab7e6154e78}
    base-url: https://api.openweathermap.org
    endpoints:
      forecast: /data/2.5/forecast
      result-count: 20


resilience4j:
  retry:
    instances:
      openWeatherRetry:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        exponentialMaxWaitDuration: 10s
        retryExceptions:
          - feign.RetryableException
          - feign.FeignException.InternalServerError
          - feign.FeignException.ServiceUnavailable
        ignoreExceptions:
          - feign.FeignException.NotFound
          
  circuitbreaker:
    instances:
      openWeatherApi:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignoreExceptions:
         - feign.FeignException.NotFound